version: "2"
services:
  python:
    build:
      context: .
    ports:
      - "8000:8000"
    #container_name: arq_py

# docker build -t arq_py .

# docker run arq_py -p 8000:8000    #PUERTO_UBUNTU:PUERTO_CONTAINER